Add py-nose to REGRESS_DEPENDS.
Before:
ImportError: Need nose >= 0.10.0 for tests - see
http://somethingaboutorange.com /mrl/projects/nose

After:
Ran 1128 tests in 5.271s
OK