BROKEN-alpha: libtomcrypt/src/headers/tomcrypt_cfg.h:130:6: error: #error You must specify a word size as well as endianess in tomcrypt_cfg.h
(this port should probably be ONLY_FOR_ARCHS=i386 amd64 since it relies
heavily on GL and blows at startup even on macppc)